on:
  workflow_run:
    workflows: ["Build and Prepare Docker Image"]
    types:
      - completed
  workflow_dispatch:

name: Deploy to Cloud Run

env:
  PROJECT_ID: able-balm-421213
  GAR_LOCATION: europe-central2
  SERVICE: ingreedio-api
  REGION: europe-west1
  REGISTRY: ghcr.io
  IMAGE_NAME: java-dzgs/ingreedio-api

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker auth for the GitHub Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull latest develop Backend image
        run: |-
           docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop
           docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-dev/ingreedio-api
        
      - name: Google auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'

      - name: Docker auth for Cloud
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
          
      - name: Docker push image to Cloud
        run: |-
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-dev/ingreedio-api
          
      - name: Deploy image to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker-dev/ingreedio-api:latest
