name: Build and Prepare Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build_and_prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Checkout your repository content into GitHub Actions runner

    - name: Docker Compose
      run: docker compose build
      # Builds the Docker image

    - name: Save Docker image
      run: docker save ingreedio-api-app -o api-image.tar
      # Saves the Docker image as a tarball

    - name: Upload Docker image as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-docker-image
        path: api-image.tar
        retention-days: 7
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Automatic build"
        files: |
          api-image.tar
