on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"
  pull_request:
    types:
      - closed

name: Release

jobs:
  release_workflow:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: gitflow-workflow-action release workflows
        uses: hoangvvo/gitflow-workflow-action@0.3.7
        with:
          develop_branch: "develop"
          main_branch: "master"
          merge_back_from_main: false
          version: ${{ inputs.version }}
          version_increment: "minor"
          dry_run: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
