on:
  workflow_dispatch:

name: Build and Deploy to Cloud Run

env:
  PROJECT_ID: able-balm-421213
  GAR_LOCATION: europe-central2
  SERVICE: YOUR_SERVICE_NAME
  REGION: YOUR_SERVICE_REGION
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'

      - name: Docker Auth for the GitHub Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull lastes Backend image
        run: |-
           docker pull ghcr.io/java-dzgs/ingreedio-api:develop

      - name: Docker Auth for Cloud
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
